title: <p align="center"> Monis Javed </p>
logo: /assets/img/profilePic.jpg.jpeg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/monis-javed-998a2629">LinkedIn</a> |
  <a href="https://github.com/mohjaved5">GitHub</a>
  
  <br>   
  I am working as a Senior Associate Technology L2 at Publicis Sapient. I am a Full stack developer with 
  expertise in .Net, Angular, ReactJs and MSSQL along with experince in cloud platforms AWS and Azure.
  <br>
  </p>

theme: jekyll-theme-minimal
